# Generated by Django 4.1.1 on 2022-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(blank=True, max_length=6, null=True)),
                ('c_summary', models.CharField(blank=True, max_length=20000, null=True)),
                ('c_name', models.CharField(blank=True, max_length=200, null=True)),
                ('c_start_dt', models.CharField(blank=True, max_length=10, null=True)),
                ('c_end_dt', models.CharField(blank=True, max_length=10, null=True)),
                ('c_fees', models.CharField(blank=True, max_length=10, null=True)),
                ('c_views', models.CharField(blank=True, max_length=10, null=True)),
                ('c_likes', models.CharField(blank=True, max_length=10, null=True)),
                ('c_total_seats', models.CharField(blank=True, max_length=10, null=True)),
                ('c_available_seats', models.CharField(blank=True, max_length=10, null=True)),
                ('c_category', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.CharField(blank=True, max_length=6, null=True)),
                ('c_id', models.CharField(blank=True, max_length=6, null=True)),
                ('l_name', models.CharField(blank=True, max_length=200, null=True)),
                ('l_dt', models.DateTimeField(blank=True)),
                ('t_id', models.CharField(blank=True, max_length=6, null=True)),
                ('l_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('l_title', models.CharField(blank=True, max_length=200, null=True)),
                ('l_download_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('l_videos', models.CharField(blank=True, max_length=2000, null=True)),
                ('l_zoom_meet', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
