# Generated by Django 4.1.1 on 2022-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_class_detail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='c_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
