# Generated by Django 4.1.1 on 2022-09-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_c_class_detail_course_c_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='coursedetails',
        ),
    ]
