# Generated by Django 4.1.1 on 2022-09-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='c_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Coursedetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursedetails'),
        ),
    ]
