# Generated by Django 4.1.1 on 2022-09-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentaffairdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_id', models.CharField(blank=True, max_length=6, null=True)),
                ('ca_link', models.CharField(blank=True, max_length=20000, null=True)),
                ('ca_text', models.CharField(blank=True, max_length=200, null=True)),
                ('c_start_dt', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='currentaffairsubsription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_id', models.CharField(blank=True, max_length=6, null=True)),
                ('cas_email', models.CharField(blank=True, max_length=20000, null=True)),
                ('cas_start_dt', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
