# Generated by Django 4.1.1 on 2022-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentaffairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaffairdetails',
            name='c_start_dt',
            field=models.CharField(blank=True, default='2022-09-18', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currentaffairsubsription',
            name='cas_start_dt',
            field=models.CharField(blank=True, default='2022-09-18', max_length=10, null=True),
        ),
    ]
