# Generated by Django 4.1.1 on 2022-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentcoursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=6, null=True)),
                ('course_id', models.CharField(blank=True, max_length=20000, null=True)),
                ('purchase_dt', models.CharField(blank=True, default='2022-09-18', max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='Payment Done', max_length=20, null=True)),
            ],
        ),
    ]
