# Generated by Django 4.1.1 on 2022-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentadditionaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=6, null=True)),
                ('address1', models.CharField(blank=True, max_length=20000, null=True)),
                ('address2', models.CharField(blank=True, max_length=20000, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
