# Generated by Django 4.1.1 on 2022-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentadditionaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursedetails',
            name='coupon',
            field=models.CharField(blank=True, default='Not Applied', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcoursedetails',
            name='discount',
            field=models.CharField(blank=True, default='0%', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcoursedetails',
            name='finalprice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
