# Generated by Django 4.1.1 on 2022-09-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_coursedetails'),
        ('student', '0003_studentcoursedetails_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursedetails',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursedetails'),
        ),
    ]
