# Generated by Django 4.1.1 on 2022-09-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentcoursedetails_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcoursedetails',
            name='course_id',
        ),
    ]
