# Generated by Django 4.1.1 on 2022-09-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentcoursedetails_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcoursedetails',
            old_name='course_id',
            new_name='Coursedetails',
        ),
    ]
